Add files via upload

diff --git a/Modulos/criarusuario b/Modulos/criarusuario
--- a/Modulos/criarusuario
+++ b/Modulos/criarusuario
@@ -1,6 +1,6 @@
 #!/bin/bash
 #====================================================
-#	@SSH-PLUS
+#	@TURBONET-PRO_SSH 
 #====================================================
 IP=$(cat /etc/IP)
 cor1='\033[41;1;37m'
@@ -257,7 +257,7 @@ tput setaf 7;tput setab 4;tput bold;printf '%30s%s%-15s\n' "CRIAR USUÁRIO SSH";
 #	echo -e "\n${cor1}Nome vazio ou invalido!${scor}\n"
 #	exit 1
 #}
-echo -ne "\033[1;32m🗣️ USUÁRIO:\033[1;37m ";read username
+echo -ne "\033[1;37mUSUÁRIO:\033[1;32m ";read username
 [[ -z $username ]] && {
 	echo -e "\n${cor1}usuário vazio ou invalido!${scor}\n"
 	exit 1
@@ -278,7 +278,7 @@ sizemax=$(echo ${#username})
 	echo -e "${cor1}use no máximo 25 caracteres!${scor}\n"
 	exit 1
 }
-echo -ne "\033[1;32m🔑 SENHA:\033[1;37m ";read password
+echo -ne "\033[1;37mSENHA:\033[1;32m ";read password
 [[ -z $password ]] && {
 	echo -e "\n${cor1}Senha vazia ou invalida!${scor}\n"
 	exit 1
@@ -288,7 +288,7 @@ sizepass=$(echo ${#password})
 	echo -e "\n${cor1}Senha curta!, use no mínimo 4 caracteres${scor}\n"
 	exit 1
 }
-echo -ne "\033[1;32m⌛ DIAS PARA EXPIRA:\033[1;37m ";read dias
+echo -ne "\033[1;37mDIAS PARA EXPIRA:\033[1;32m ";read dias
 [[ -z $dias ]] && {
 	echo -e "\n${cor1}Numero de dias vazio!${scor}\n"
 	exit 1
@@ -301,7 +301,7 @@ echo -ne "\033[1;32m⌛ DIAS PARA EXPIRA:\033[1;37m ";read dias
 	echo -e "\n${cor1}O número deve ser maior que zero!${scor}\n"
 	exit 1
 }
-echo -ne "\033[1;32m📲 LIMITE DE CONEXÕES:\033[1;37m ";read sshlimiter
+echo -ne "\033[1;37mLIMITE DE CONEXÕES:\033[1;32m ";read sshlimiter
 [[ -z $sshlimiter ]] && {
 	echo -e "\n${cor1}Você deixou o limite de conexões vazio!${scor}\n"
 	exit 1
@@ -312,6 +312,11 @@ echo -ne "\033[1;32m📲 LIMITE DE CONEXÕES:\033[1;37m ";read sshlimiter
 }
 [[ $sshlimiter -lt 1 ]] && {
 	echo -e "\n${cor1}Número de conexões simultâneas deve ser maior que zero!${scor}\n"
+	exit 1
+}
+echo -ne "\033[1;37mVALOR:\033[1;32m ";read vl
+[[ -z $vl ]] && {
+	echo -e "\n${cor1}Valor vazio ou invalido!${scor}\n"
 	exit 1
 }
 final=$(date "+%Y-%m-%d" -d "+$dias days")
@@ -341,12 +346,12 @@ echo "$username $sshlimiter" >>/root/usuarios.db
 			}
 		}
 		clear
-		#echo -e "\033[1;32m 📝NOME: \033[1;37m$nomee"
-		echo -e "\E[44;1;37m======🦸DADOS DE ACESSO🦸‍♀️======\E[0m"
-		echo -e "\033[1;32m 🗣️USUARIO: \033[1;37m$username"
-		echo -e "\033[1;32m 🔑SENHA: \033[1;37m$password"
-		echo -e "\033[1;32m ⌛EXPIRA EM: \033[1;37m$gui"
-		echo -e "\033[1;32m 📲LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
+		#echo -e "\033[1;32m NOME: \033[1;37m$nomee"
+		echo -e "\E[44;1;37m======DADOS DE ACESSO======\E[0m"
+		echo -e "\033[1;32m ️USUARIO: \033[1;37m$username"
+		echo -e "\033[1;32m SENHA: \033[1;37m$password"
+		echo -e "\033[1;32m EXPIRA EM: \033[1;37m$gui"
+		echo -e "\033[1;32m LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
 		sleep 1
 		function aguarde() {
 			helice() {
@@ -381,21 +386,21 @@ echo "$username $sshlimiter" >>/root/usuarios.db
 		}
 	} || {
 		clear
-		#echo -e "\033[1;32m 📝NOME: \033[1;37m$nomee"
-		echo -e "\E[44;1;37m======🦸DADOS DE ACESSO🦸‍♀️======\E[0m"
-		echo -e "\033[1;32m 🗣️USUARIO: \033[1;37m$username"
-		echo -e "\033[1;32m 🔑SENHA: \033[1;37m$password"
-		echo -e "\033[1;32m ⌛EXPIRA EM: \033[1;37m$gui"
-		echo -e "\033[1;32m 📲LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
+		#echo -e "\033[1;32m NOME: \033[1;37m$nomee"
+		echo -e "\E[44;1;37m======DADOS DE ACESSO======\E[0m"
+		echo -e "\033[1;32m ️USUARIO: \033[1;37m$username"
+		echo -e "\033[1;32m SENHA: \033[1;37m$password"
+		echo -e "\033[1;32m EXPIRA EM: \033[1;37m$gui"
+		echo -e "\033[1;32m LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
 echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
 	}
 } || {
 	clear
-		#echo -e "\033[1;32m 📝NOME: \033[1;37m$nomee"
-		echo -e "\E[44;1;37m======🦸DADOS DE ACESSO🦸‍♀️======\E[0m"
-		echo -e "\033[1;32m 🗣️USUARIO: \033[1;37m$username"
-		echo -e "\033[1;32m 🔑SENHA: \033[1;37m$password"
-		echo -e "\033[1;32m ⌛EXPIRA EM: \033[1;37m$gui"
-		echo -e "\033[1;32m 📲LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
+		#echo -e "\033[1;32m NOME: \033[1;37m$nomee"
+		echo -e "\E[44;1;37m======DADOS DE ACESSO======\E[0m"
+		echo -e "\033[1;32m USUARIO: \033[1;37m$username"
+		echo -e "\033[1;32m SENHA: \033[1;37m$password"
+		echo -e "\033[1;32m EXPIRA EM: \033[1;37m$gui"
+		echo -e "\033[1;32m LIMITE DE CONEXÃO: \033[1;37m$sshlimiter"
 echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
 }
